name: Generate Snake

# Controls when the action will run. This action runs every 3 hours (to help build the snake faster)
on:
  schedule:
    # every 3 hours instead of 6
    - cron: "0 */3 * * *"

  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks out the code so the job can access it
    - uses: actions/checkout@v2

    # Generates the snake gif with Platane's action
    - uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: ralphndr
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg
        # Added to ensure all commits are captured in the snake, customize the days parameter if needed
        days: 365  # Optionally extend the date range for which you want the contributions to be shown

    # Show the status of the build (for debugging purposes)
    - run: git status

    # Commit and push the changes to the output branch
    - name: Commit and push snake image
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add dist/*
        git commit -m "Update contribution snake gif"
        git push origin master

    # Use GitHub Pages to serve the generated snake
    - uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
