name: Snake

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not `main`
  schedule:
    - cron: "0 0 * * *"  # This runs the action once every day, adjust if needed

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user: ${{ github.actor }}
          # Change the repository name if you want it to be in a different repo.
          image: "true"

      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: snake.svg

