name: Snake Animation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-snake-animation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user: ralphndr
          output: dist
          color: blue
          model: octocat

      - name: Commit snake animation
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Ralph Nader
          author_email: ralph.nader@outlook.com
          message: "Update snake animation"
          add: "dist/snake.svg"


